os:
  - linux

language: python

jobs:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

before_install:
 - sudo apt-get update
 - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
   else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
   fi
 - bash miniconda.sh -b -p $HOME/miniconda
 - source "$HOME/miniconda/etc/profile.d/conda.sh"
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update conda
 # Useful for debugging any issues with conda
 - conda info -a

 # Add specific python version to conda environment file
 - sed -i -e "s/python=3/python=$TRAVIS_PYTHON_VERSION/" environment.yml
 # Create conda environment with required dependencies
 - conda env create -n test_env environment.yml
 - conda activate test_env

 # Install coveralls
 - pip install coveralls

install:
 # Install
 - python setup.py build_ext --inplace
 - python setup.py install

 # Get optional dependencies
 - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install futures;
   fi
 - conda install mpi4py h5py
 - pip install standardiser

 # Get packages for testing
 - conda install nose mock

script:
 # Run all tests
 - nosetests --with-coverage --with-doctest --doctest-options=+ELLIPSIS e3fp;

after_success:
 # Run Coveralls
 - coveralls
