os:
  - linux

language: python
python:
 # We don't actually use the Travis Python, but this keeps it organized.
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

matrix:
  include:
    # Python for osx currently not supported. We don't need it anyways.
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
   else
      sudo apt-get update;
      if [[ "$PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    fi
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 # Useful for debugging any issues with conda
 - conda info -a

 # Add specific python version to conda environment file
 - sed -i -e "s/python=3/python=$TRAVIS_PYTHON_VERSION/" environment.yml
 # Create conda environment with required dependencies
 - conda env create -q -n test_env environment.yml
 - source activate test_env

 # Install coveralls
 - pip install python-coveralls

install: 
 # Install
 - python setup.py build_ext --inplace
 - python setup.py install

 # Get optional dependencies
 - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install -q futures;
   fi
 - conda install -q mpi4py h5py 
 - pip install -q standardiser
 
 # Get packages for testing
 - conda install -q nose mock

script:
 # Run all tests with coverage
 - nosetests --with-coverage e3fp

after_success:
  # Run Coveralls
 - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      coveralls;
   fi

